// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package com.example.grpc2.stubs;

public interface DeleteCompteByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteCompteByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Indique si la suppression a réussi
   * </pre>
   *
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
