// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CompteService.proto

package com.example.grpc2.stubs;

public interface GetComptesByTypeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetComptesByTypeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Type de compte demandé
   * </pre>
   *
   * <code>.TypeCompte type = 1;</code>
   * @return The enum numeric value on the wire for type.
   */
  int getTypeValue();
  /**
   * <pre>
   * Type de compte demandé
   * </pre>
   *
   * <code>.TypeCompte type = 1;</code>
   * @return The type.
   */
  com.example.grpc2.stubs.TypeCompte getType();
}
